<?xml version="1.0"?>
<package format="2">
  <name>rosbot_simulation</name>
  <version>0.1.0</version>
  <description>Gazebo simulation assets and sim adapters for ROSbot competition.</description>

  <maintainer email="dev@example.com">ROSbot Dev</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>gazebo_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>rosbot_competition_msgs</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>std_srvs</build_depend>
  <build_depend>xacro</build_depend>

  <exec_depend>gazebo_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rosbot_competition_msgs</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export/>
</package>
