topics:
  - name: ir_safety
    topic: ir_cmd_vel
    timeout: 0.5
    priority: 100
  - name: visual_servo
    topic: servo_cmd_vel
    timeout: 0.5
    priority: 50
  - name: navigation
    topic: move_base/cmd_vel
    timeout: 0.5
    priority: 10
