topics:
  - name: ir_safety
    topic: cmd_vel_safety
    timeout: 0.5
    priority: 100
  - name: visual_servo
    topic: cmd_vel_servo
    timeout: 0.5
    priority: 50
  - name: navigation
    topic: cmd_vel_nav
    timeout: 0.5
    priority: 10

locks: []
